### ISSUE TITLE
Promises PSR?

### ISSUE THREAD

**Issue by bshaffer** [php-http/promise#17]
The README mentions an "upcoming Promises PSR". What is the news for this?

**Comment by dbu** [comment]
i did not hear anything about that anymore. but i am not closely involved with the FIG. please inquire at the FIG, contacts are listed at the bottom of https://www.php-fig.org/

i would be glad to switch this to something based on a promise PSR - as we say in PSR-18 we have not been able to define async http clients because that requires promises and we did not want PSR-18 to define promises as it would be massively out of scope.
