### ISSUE TITLE
Do we want to make unwrapping optional

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/promise#2]
With the unwrap parameter unwrapping became optional. Do we want that? Do we need that?

Guzzle does that, but after some time, I am not so sure about it anymore.

**Comment by joelwurtz** [comment]
Can be useful to not wrap when you only want your callbacks to be called and don't want to handle the exception with a try catch.

**Comment by dbu** [comment]
i think we should only offer one of the two, to reduce complexity.
its just two different coding styles and you can easily convert between the two in your client code. i would opt for throwing the exception, but can leave with returning it.

**Comment by sagikazarmark** [comment]
I am also in favor of throwing one.

Pros:

- Single behavior
- Possible match with the upcoming PSR

Cons:

- Wait method calls always must be encapsulated in a try-catch (which I wonder if it's really a con, because in many cases that exception would be thrown anyway I think)

**Comment by sagikazarmark** [comment]
I would say: if we can't find any wait methods with a false argument, drop it entirely.

**Comment by joelwurtz** [comment]
> Wait method calls always must be encapsulated in a try-catch (which I wonder if it's really a con, because in many cases that exception would be thrown anyway I think)

That's really a con, because normally you don't have to catch the HttpException if using callables and you don't mind about the wait result.

**Comment by sagikazarmark** [comment]
What do you propose? Single responsibility should be the goal IMO.

Add an unwrap method?

**Comment by joelwurtz** [comment]
I think that's way in the first place i write a wait method with no return and the getException / getResponse methods.

Really don't like the unwrap method (for the name), but if there is another name that sound goods :+1:

**Comment by sagikazarmark** [comment]
Hm, I think the getResponse and getException methods has been removed because of two reasons:

1. During unwrapping you don't want to know if it's an exception or a response. If you need to handle them, use try-catch.
2. Possible future compatibility with a Promise PSR.

Am I right when I say one shouldn't even call wait multiple times? Doing so would restart the whole process in theory, wouldn't it?

**Comment by joelwurtz** [comment]
No, the wait method is more like an idempotent state: you want the promise to be resolved but it may be already resolved or not. If there is multiple calls to the wait method, the whole process should not be restarted.

**Comment by dbu** [comment]
i think calling wait again would just immediately return the result once its there, not restart.

if we return the exception rather than throw it, we don't need a parameter for wait() anymore. we can simply always return it - if the user relies on callback and ignores the return, there is no harm.

https://promisesaplus.com/ does not speak about wait. i think we really need that for php however. whether that method should return values, throw exception or use separate getters, or a single getter... i really don't know. does the PSR discussion give any hints? if not, i would go with unconditionally returning exception/result in wait. upgrading to the psr promise will be a BC break regardless of what we chose now...

**Comment by sagikazarmark** [comment]
Unfortunately the PSR discussion stopped a few months ago. It seems to me that there is more demand for an event loop PSR.

This interface however looks promising:

https://github.com/thenable/promise

I agree with @dbu. We already stated in the documentation that the promise interface will be replaced once. That itself requires a major version bump.

Before releasing the library with this solution, we should make sure that every plugin works with it. We probably have to release 0.2 promise and 1.0-beta2 httplug to do so.

**Comment by joelwurtz** [comment]
In fact there is no need for a wait method if we have an Event Loop. So the futur PSR will certainly only have the then method / getState method (but no wait).

That's why i think we must not bother too much that and just provide something that works. IMO the current function is OK and we must not think too hard about this. (and IMO there is only one responsability, it's just a parameter for the user to choose what kind of return type he wants)

**Comment by sagikazarmark** [comment]
> we must not think too hard about this

:+1: 

Okay, so returning instead of throwing exceptions vs leaving as is?

**Comment by joelwurtz** [comment]
:+1: leaving as is, both use case make sense for me, and the default one is the most used

**Comment by sagikazarmark** [comment]
Fine by me, I don't have a better idea.
